[Host.py:118 (thread: MainThread)]:DEBUG: start rpc server
[Host.py:90 (thread: MainThread)]:DEBUG: Opening socket /tmp/overlordsockets/host3
[Host.py:94 (thread: MainThread)]:DEBUG: create transport
[Host.py:100 (thread: MainThread)]:DEBUG: create result
[Host.py:120 (thread: MainThread)]:DEBUG: <thrift.server.TServer.TSimpleServer instance at 0x7fd61d9093b0>.serve()
[Host.py:35 (thread: MainThread)]:DEBUG: host3.startRunnable(KademliaBot,{u'peerlist': [u'10.0.0.2'], u'name': u'host3'})
[KademliaBot.py:91 (thread: Runnable KademliaBot)]:DEBUG: Start the KademliaBot host3 on port 8468
[KademliaBot.py:106 (thread: Runnable KademliaBot)]:DEBUG: Interfaces: {17: [{'broadcast': 'ff:ff:ff:ff:ff:ff', 'addr': 'ea:98:5f:ac:72:e5'}], 2: [{'broadcast': '10.255.255.255', 'netmask': '255.0.0.0', 'addr': '10.0.0.3'}], 10: [{'netmask': 'ffff:ffff:ffff:ffff::', 'addr': 'fe80::e898:5fff:feac:72e5%host3-eth0'}]}
[KademliaBot.py:108 (thread: Runnable KademliaBot)]:DEBUG: Node host3 starts with [u'10.0.0.2'] on 10.0.0.3
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: KademliaProtocol starting on 8468
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] creating spider with peers: [[324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468]]
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] crawling with nearest: ([324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468],)
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.2:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] creating spider with peers: [[324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468]]
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] crawling with nearest: ([324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468],)
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.2:8468, adding to router
[KademliaBot.py:123 (thread: Runnable KademliaBot)]:DEBUG: Got (new?) command: None
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 990742406389957732913686416881918796971713285270 in local table
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 990742406389957732913686416881918796971713285270 in local table
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 765978881870936217673365922905375815677236244626 in local table
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 765978881870936217673365922905375815677236244626 in local table
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 324804616546447175140291206854963413400425823390 in local table
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] creating spider with peers: [[990742406389957732913686416881918796971713285270L, '10.0.0.4', 8468], [765978881870936217673365922905375815677236244626L, '10.0.0.5', 8468], [324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468]]
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] crawling with nearest: ([990742406389957732913686416881918796971713285270L, '10.0.0.4', 8468], [765978881870936217673365922905375815677236244626L, '10.0.0.5', 8468], [324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468])
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.5:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.4:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.2:8468, adding to router
[KademliaBot.py:123 (thread: Runnable KademliaBot)]:DEBUG: Got (new?) command: None
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 990742406389957732913686416881918796971713285270 in local table
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 765978881870936217673365922905375815677236244626 in local table
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] finding neighbors of 324804616546447175140291206854963413400425823390 in local table
[KademliaBot.py:45 (thread: Runnable KademliaBot)]:DEBUG: Received POST: ddos_server != default_command == True
[KademliaBot.py:52 (thread: Runnable KademliaBot)]:DEBUG: The KademliaBot has received a new command: 
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [DEBUG] setting 'current_command' = '{"command": "ddos_server", "kwargs": {"url": "http://10.0.0.6:8080/ddos_me"}}' on network
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] creating spider with peers: [[990742406389957732913686416881918796971713285270L, '10.0.0.4', 8468], [765978881870936217673365922905375815677236244626L, '10.0.0.5', 8468], [324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468]]
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] crawling with nearest: ([990742406389957732913686416881918796971713285270L, '10.0.0.4', 8468], [765978881870936217673365922905375815677236244626L, '10.0.0.5', 8468], [324804616546447175140291206854963413400425823390L, u'10.0.0.2', 8468])
[web.py:1908 (thread: Runnable KademliaBot)]:INFO: 200 POST /current_command (10.0.0.3) 3.71ms
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.4:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.2:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.5:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] setting 'current_command' on ['10.0.0.4:8468', '10.0.0.5:8468', '10.0.0.2:8468']
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.4:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.5:8468, adding to router
[_legacy.py:154 (thread: Runnable KademliaBot)]:INFO: [INFO] got response from 10.0.0.2:8468, adding to router
[KademliaBot.py:63 (thread: Runnable KademliaBot)]:DEBUG: Result of successful set command: True
[KademliaBot.py:123 (thread: Runnable KademliaBot)]:DEBUG: Got (new?) command: {"command": "ddos_server", "kwargs": {"url": "http://10.0.0.6:8080/ddos_me"}}
[KademliaBot.py:123 (thread: Runnable KademliaBot)]:DEBUG: Got (new?) command: {"command": "ddos_server", "kwargs": {"url": "http://10.0.0.6:8080/ddos_me"}}
[Host.py:35 (thread: MainThread)]:DEBUG: host3.startRunnable(Victim,{})
[Host.py:35 (thread: MainThread)]:DEBUG: host3.startRunnable(Victim,{})
